apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: $(prodWebrouterTag)
  name: $(prodWebrouterTag)
  namespace: default
spec:
  ports:
    - name: server
      targetPort: $(prodWebrouterPort)
      port: $(prodWebrouterPort)
  selector:
    k8s-app: $(prodWebrouterTag)
