apiVersion: v1
kind: ReplicationController
metadata:
  name: $(stagingWebsocketerTag)
  namespace: default
  labels:
    k8s-app: $(stagingWebsocketerTag)
spec:
  replicas: 1
  selector:
    k8s-app: $(stagingWebsocketerTag)
  template:
    metadata:
      labels:
        k8s-app: $(stagingWebsocketerTag)
    spec:
      nodeName: $(stagingDockerHost)
      containers:
        - name: $(stagingWebsocketerTag)
          image: $(registryServer)/$(stagingWebsocketerTag):$(dockerVersion)
          imagePullPolicy: Always
          ports:
            - name: server
              containerPort: $(stagingWebsocketerPort)
          env:
            - name: APP_NAME
              value: "$(stagingWebsocketerTag)"
            - name: VIRTUAL_HOST
              value: "$(stagingWebsocketerHost)"
            - name: VIRTUAL_PORT
              value: "$(stagingWebsocketerPort)"
            - name: VIRTUAL_NAME
              value: "$(stagingWebsocketerVirtualName)"
          resources:
            limits:
              memory: 1G
